<?php

if ( function_exists( 'acf_add_local_field_group' ) ) :

	acf_add_local_field_group(
		array(
			'key'                   => 'group_5adef3b24d155',
			'title'                 => 'Hintergrund',
			'fields'                => array(
				array(
					'key'               => 'field_5adef3c6794a7',
					'label'             => 'Hintergrund',
					'name'              => 'background',
					'type'              => 'select',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'choices'           => array(
						'white' => 'weiß',
						'green' => 'grün',
						'none'  => 'kein',
					),
					'default_value'     => array(),
					'allow_null'        => 0,
					'multiple'          => 0,
					'ui'                => 0,
					'ajax'              => 0,
					'return_format'     => 'value',
					'placeholder'       => '',
				),
			),
			'location'              => array(
				array(
					array(
						'param'    => 'page_parent',
						'operator' => '==',
						'value'    => '2',
					),
				),
			),
			'menu_order'            => 0,
			'position'              => 'normal',
			'style'                 => 'seamless',
			'label_placement'       => 'top',
			'instruction_placement' => 'label',
			'hide_on_screen'        => array(
				0 => 'the_content',
				1 => 'comments',
				2 => 'send-trackbacks',
			),
			'active'                => 1,
			'description'           => '',
		)
	);

	acf_add_local_field_group(
		array(
			'key'                   => 'group_5acca7ecc2ceb',
			'title'                 => 'Beans and Books Flexible Inhalte',
			'fields'                => array(
				array(
					'key'               => 'field_5acca86c80a08',
					'label'             => 'Flexible Inhalte',
					'name'              => 'flexible',
					'type'              => 'flexible_content',
					'instructions'      => '',
					'required'          => 1,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'layouts'           => array(
						'5acca89fee45b' => array(
							'key'        => '5acca89fee45b',
							'name'       => 'intro_text',
							'label'      => 'Startseite Intro-Text',
							'display'    => 'block',
							'sub_fields' => array(
								array(
									'key'               => 'field_5acca8fb80a09',
									'label'             => 'Intro-Text',
									'name'              => 'intro_text',
									'type'              => 'textarea',
									'instructions'      => '',
									'required'          => 1,
									'conditional_logic' => 0,
									'wrapper'           => array(
										'width' => '',
										'class' => '',
										'id'    => '',
									),
									'default_value'     => '',
									'placeholder'       => '',
									'maxlength'         => '',
									'rows'              => 4,
									'new_lines'         => '',
								),
							),
							'min'        => '',
							'max'        => '',
						),
						'5acca96880a0c' => array(
							'key'        => '5acca96880a0c',
							'name'       => 'slider',
							'label'      => 'Slider',
							'display'    => 'block',
							'sub_fields' => array(
								array(
									'key'               => 'field_5acca98880a0d',
									'label'             => 'Slider',
									'name'              => 'slider',
									'type'              => 'gallery',
									'instructions'      => '',
									'required'          => 1,
									'conditional_logic' => 0,
									'wrapper'           => array(
										'width' => '',
										'class' => '',
										'id'    => '',
									),
									'min'               => '',
									'max'               => '',
									'insert'            => 'append',
									'library'           => 'all',
									'min_width'         => '',
									'min_height'        => '',
									'min_size'          => '',
									'max_width'         => '',
									'max_height'        => '',
									'max_size'          => '',
									'mime_types'        => '',
								),
							),
							'min'        => '',
							'max'        => '',
						),
						'5acca95280a0b' => array(
							'key'        => '5acca95280a0b',
							'name'       => 'editor',
							'label'      => 'Editor',
							'display'    => 'block',
							'sub_fields' => array(
								array(
									'key'               => 'field_5accaa1380a0e',
									'label'             => 'Editor',
									'name'              => 'editor',
									'type'              => 'wysiwyg',
									'instructions'      => '',
									'required'          => 1,
									'conditional_logic' => 0,
									'wrapper'           => array(
										'width' => '',
										'class' => '',
										'id'    => '',
									),
									'default_value'     => '',
									'tabs'              => 'all',
									'toolbar'           => 'full',
									'media_upload'      => 1,
									'delay'             => 0,
								),
							),
							'min'        => '',
							'max'        => '',
						),
						'5accaae380a0f' => array(
							'key'        => '5accaae380a0f',
							'name'       => 'accordion',
							'label'      => 'Accordion',
							'display'    => 'block',
							'sub_fields' => array(
								array(
									'key'               => 'field_5accab5680a10',
									'label'             => 'Accordion-Eintrag',
									'name'              => 'items',
									'type'              => 'repeater',
									'instructions'      => '',
									'required'          => 1,
									'conditional_logic' => 0,
									'wrapper'           => array(
										'width' => '',
										'class' => '',
										'id'    => '',
									),
									'collapsed'         => '',
									'min'               => 1,
									'max'               => 0,
									'layout'            => 'block',
									'button_label'      => '',
									'sub_fields'        => array(
										array(
											'key'          => 'field_5accac3780a11',
											'label'        => 'Überschrift',
											'name'         => 'headline',
											'type'         => 'text',
											'instructions' => '',
											'required'     => 1,
											'conditional_logic' => 0,
											'wrapper'      => array(
												'width' => '',
												'class' => '',
												'id'    => '',
											),
											'default_value' => '',
											'placeholder'  => '',
											'prepend'      => '',
											'append'       => '',
											'maxlength'    => '',
										),
										array(
											'key'          => 'field_5accacd080a12',
											'label'        => 'Inhalt',
											'name'         => 'content',
											'type'         => 'repeater',
											'instructions' => '',
											'required'     => 1,
											'conditional_logic' => 0,
											'wrapper'      => array(
												'width' => '',
												'class' => '',
												'id'    => '',
											),
											'collapsed'    => '',
											'min'          => 1,
											'max'          => 0,
											'layout'       => 'block',
											'button_label' => '',
											'sub_fields'   => array(
												array(
													'key'  => 'field_5accad9380a15',
													'label' => 'Bild',
													'name' => 'img',
													'type' => 'image',
													'instructions' => '',
													'required' => 0,
													'conditional_logic' => 0,
													'wrapper' => array(
														'width' => '',
														'class' => '',
														'id' => '',
													),
													'return_format' => 'id',
													'preview_size' => 'thumbnail',
													'library' => 'all',
													'min_width' => '',
													'min_height' => '',
													'min_size' => '',
													'max_width' => '',
													'max_height' => '',
													'max_size' => '',
													'mime_types' => '',
												),
												array(
													'key'  => 'field_5accad3980a13',
													'label' => 'Titel',
													'name' => 'title',
													'type' => 'text',
													'instructions' => '',
													'required' => 0,
													'conditional_logic' => 0,
													'wrapper' => array(
														'width' => '',
														'class' => '',
														'id' => '',
													),
													'default_value' => '',
													'placeholder' => '',
													'prepend' => '',
													'append' => '',
													'maxlength' => '',
												),
												array(
													'key'  => 'field_5accad6f80a14',
													'label' => 'Text',
													'name' => 'text',
													'type' => 'wysiwyg',
													'instructions' => '',
													'required' => 0,
													'conditional_logic' => 0,
													'wrapper' => array(
														'width' => '75',
														'class' => '',
														'id' => '',
													),
													'default_value' => '',
													'tabs' => 'all',
													'toolbar' => 'basic',
													'media_upload' => 0,
													'delay' => 0,
												),
												array(
													'key'  => 'field_5accae3e80a16',
													'label' => 'Preis',
													'name' => 'price',
													'type' => 'text',
													'instructions' => '',
													'required' => 0,
													'conditional_logic' => 0,
													'wrapper' => array(
														'width' => '25',
														'class' => '',
														'id' => '',
													),
													'default_value' => '',
													'placeholder' => '',
													'prepend' => '',
													'append' => '',
													'maxlength' => '',
												),
												array(
													'key'  => 'field_5ae1929ead6ae',
													'label' => 'Menükarte nach Wahl',
													'name' => 'include',
													'type' => 'true_false',
													'instructions' => '',
													'required' => 0,
													'conditional_logic' => 0,
													'wrapper' => array(
														'width' => '',
														'class' => '',
														'id' => '',
													),
													'message' => '',
													'default_value' => 0,
													'ui'   => 1,
													'ui_on_text' => '',
													'ui_off_text' => '',
												),
											),
										),
									),
								),
							),
							'min'        => '',
							'max'        => '',
						),
						'5ad9a9f70eca9' => array(
							'key'        => '5ad9a9f70eca9',
							'name'       => 'selected',
							'label'      => 'Erlesenes',
							'display'    => 'block',
							'sub_fields' => array(
								array(
									'key'               => 'field_5ad9aca10ecaa',
									'label'             => 'Text',
									'name'              => 'text',
									'type'              => 'text',
									'instructions'      => '',
									'required'          => 1,
									'conditional_logic' => 0,
									'wrapper'           => array(
										'width' => '',
										'class' => '',
										'id'    => '',
									),
									'default_value'     => '',
									'placeholder'       => '',
									'prepend'           => '',
									'append'            => '',
									'maxlength'         => '',
								),
								array(
									'key'               => 'field_5ad9ad0b0ecab',
									'label'             => 'Bild',
									'name'              => 'img',
									'type'              => 'image',
									'instructions'      => '',
									'required'          => 1,
									'conditional_logic' => 0,
									'wrapper'           => array(
										'width' => '',
										'class' => '',
										'id'    => '',
									),
									'return_format'     => 'id',
									'preview_size'      => 'thumbnail',
									'library'           => 'all',
									'min_width'         => '',
									'min_height'        => '',
									'min_size'          => '',
									'max_width'         => '',
									'max_height'        => '',
									'max_size'          => '',
									'mime_types'        => '',
								),
							),
							'min'        => '',
							'max'        => '',
						),
						'5acf3f7b455d7' => array(
							'key'        => '5acf3f7b455d7',
							'name'       => 'team',
							'label'      => 'Team',
							'display'    => 'block',
							'sub_fields' => array(
								array(
									'key'               => 'field_5acf3f93455d8',
									'label'             => 'Team',
									'name'              => 'team',
									'type'              => 'repeater',
									'instructions'      => '',
									'required'          => 1,
									'conditional_logic' => 0,
									'wrapper'           => array(
										'width' => '',
										'class' => '',
										'id'    => '',
									),
									'collapsed'         => '',
									'min'               => 1,
									'max'               => 0,
									'layout'            => 'block',
									'button_label'      => 'Person hinzufügen',
									'sub_fields'        => array(
										array(
											'key'          => 'field_5acf3fbf455d9',
											'label'        => 'Name',
											'name'         => 'name',
											'type'         => 'text',
											'instructions' => '',
											'required'     => 1,
											'conditional_logic' => 0,
											'wrapper'      => array(
												'width' => '',
												'class' => '',
												'id'    => '',
											),
											'default_value' => '',
											'placeholder'  => '',
											'prepend'      => '',
											'append'       => '',
											'maxlength'    => '',
										),
										array(
											'key'          => 'field_5acf3fe1455da',
											'label'        => 'Text',
											'name'         => 'text',
											'type'         => 'textarea',
											'instructions' => '',
											'required'     => 0,
											'conditional_logic' => 0,
											'wrapper'      => array(
												'width' => '',
												'class' => '',
												'id'    => '',
											),
											'default_value' => '',
											'placeholder'  => '',
											'maxlength'    => '',
											'rows'         => '',
											'new_lines'    => '',
										),
										array(
											'key'          => 'field_5acf3ffb455db',
											'label'        => 'Bild',
											'name'         => 'img',
											'type'         => 'image',
											'instructions' => '',
											'required'     => 0,
											'conditional_logic' => 0,
											'wrapper'      => array(
												'width' => '',
												'class' => '',
												'id'    => '',
											),
											'return_format' => 'id',
											'preview_size' => 'thumbnail',
											'library'      => 'all',
											'min_width'    => '',
											'min_height'   => '',
											'min_size'     => '',
											'max_width'    => '',
											'max_height'   => '',
											'max_size'     => '',
											'mime_types'   => '',
										),
									),
								),
							),
							'min'        => '',
							'max'        => '',
						),
						'5ad859c9775b3' => array(
							'key'        => '5ad859c9775b3',
							'name'       => 'news',
							'label'      => 'Aktuelles',
							'display'    => 'block',
							'sub_fields' => array(
								array(
									'key'               => 'field_5ad859f0775b4',
									'label'             => 'Aktuelles anzeigen?',
									'name'              => 'news',
									'type'              => 'true_false',
									'instructions'      => '',
									'required'          => 1,
									'conditional_logic' => 0,
									'wrapper'           => array(
										'width' => '',
										'class' => '',
										'id'    => '',
									),
									'message'           => '',
									'default_value'     => 1,
									'ui'                => 1,
									'ui_on_text'        => '',
									'ui_off_text'       => '',
								),
							),
							'min'        => '',
							'max'        => '',
						),
						'5ad59bf4f1a86' => array(
							'key'        => '5ad59bf4f1a86',
							'name'       => 'location',
							'label'      => 'Ort',
							'display'    => 'block',
							'sub_fields' => array(
								array(
									'key'               => 'field_5ad59d52f1a87',
									'label'             => 'Name',
									'name'              => 'name',
									'type'              => 'text',
									'instructions'      => '',
									'required'          => 1,
									'conditional_logic' => 0,
									'wrapper'           => array(
										'width' => '',
										'class' => '',
										'id'    => '',
									),
									'default_value'     => '',
									'placeholder'       => '',
									'prepend'           => '',
									'append'            => '',
									'maxlength'         => '',
								),
								array(
									'key'               => 'field_5ad59f33f1a88',
									'label'             => 'Alternativer Name',
									'name'              => 'altname',
									'type'              => 'text',
									'instructions'      => '',
									'required'          => 0,
									'conditional_logic' => 0,
									'wrapper'           => array(
										'width' => '',
										'class' => '',
										'id'    => '',
									),
									'default_value'     => '',
									'placeholder'       => '',
									'prepend'           => '',
									'append'            => '',
									'maxlength'         => '',
								),
								array(
									'key'               => 'field_5ad59f76f1a89',
									'label'             => 'Straße, Nr.',
									'name'              => 'street',
									'type'              => 'text',
									'instructions'      => '',
									'required'          => 1,
									'conditional_logic' => 0,
									'wrapper'           => array(
										'width' => '',
										'class' => '',
										'id'    => '',
									),
									'default_value'     => '',
									'placeholder'       => '',
									'prepend'           => '',
									'append'            => '',
									'maxlength'         => '',
								),
								array(
									'key'               => 'field_5ad59fb3f1a8a',
									'label'             => 'PLZ',
									'name'              => 'zipcode',
									'type'              => 'text',
									'instructions'      => '',
									'required'          => 1,
									'conditional_logic' => 0,
									'wrapper'           => array(
										'width' => '25',
										'class' => '',
										'id'    => '',
									),
									'default_value'     => '',
									'placeholder'       => '',
									'prepend'           => '',
									'append'            => '',
									'maxlength'         => '',
								),
								array(
									'key'               => 'field_5ad59fd3f1a8b',
									'label'             => 'Ort',
									'name'              => 'location',
									'type'              => 'text',
									'instructions'      => '',
									'required'          => 1,
									'conditional_logic' => 0,
									'wrapper'           => array(
										'width' => '75',
										'class' => '',
										'id'    => '',
									),
									'default_value'     => '',
									'placeholder'       => '',
									'prepend'           => '',
									'append'            => '',
									'maxlength'         => '',
								),
								array(
									'key'               => 'field_5ad5a257f1a8c',
									'label'             => 'Telefon',
									'name'              => 'tel',
									'type'              => 'text',
									'instructions'      => '',
									'required'          => 0,
									'conditional_logic' => 0,
									'wrapper'           => array(
										'width' => '',
										'class' => '',
										'id'    => '',
									),
									'default_value'     => '',
									'placeholder'       => '',
									'prepend'           => '',
									'append'            => '',
									'maxlength'         => '',
								),
								array(
									'key'               => 'field_5ad5a281f1a8d',
									'label'             => 'Fax',
									'name'              => 'fax',
									'type'              => 'text',
									'instructions'      => '',
									'required'          => 0,
									'conditional_logic' => 0,
									'wrapper'           => array(
										'width' => '',
										'class' => '',
										'id'    => '',
									),
									'default_value'     => '',
									'placeholder'       => '',
									'prepend'           => '',
									'append'            => '',
									'maxlength'         => '',
								),
								array(
									'key'               => 'field_5ad5a297f1a8e',
									'label'             => 'E-Mail',
									'name'              => 'email',
									'type'              => 'email',
									'instructions'      => '',
									'required'          => 0,
									'conditional_logic' => 0,
									'wrapper'           => array(
										'width' => '',
										'class' => '',
										'id'    => '',
									),
									'default_value'     => '',
									'placeholder'       => '',
									'prepend'           => '',
									'append'            => '',
								),
								array(
									'key'               => 'field_5ad5a2cbf1a8f',
									'label'             => 'Karte',
									'name'              => 'coords',
									'type'              => 'google_map',
									'instructions'      => '',
									'required'          => 0,
									'conditional_logic' => 0,
									'wrapper'           => array(
										'width' => '',
										'class' => '',
										'id'    => '',
									),
									'center_lat'        => '',
									'center_lng'        => '',
									'zoom'              => '',
									'height'            => '',
								),
							),
							'min'        => '',
							'max'        => '',
						),
						'5ae1b3c2cbb37' => array(
							'key'        => '5ae1b3c2cbb37',
							'name'       => 'openinghrs',
							'label'      => 'Öffnungszeiten',
							'display'    => 'block',
							'sub_fields' => array(
								array(
									'key'               => 'field_5ae1b451cbb38',
									'label'             => 'Öffnungszeiten',
									'name'              => 'openinghrs',
									'type'              => 'textarea',
									'instructions'      => '',
									'required'          => 1,
									'conditional_logic' => 0,
									'wrapper'           => array(
										'width' => '',
										'class' => '',
										'id'    => '',
									),
									'default_value'     => '',
									'placeholder'       => '',
									'maxlength'         => '',
									'rows'              => 4,
									'new_lines'         => 'wpautop',
								),
							),
							'min'        => '',
							'max'        => '',
						),
					),
					'button_label'      => 'Inhalt hinzufügen',
					'min'               => 1,
					'max'               => '',
				),
			),
			'location'              => array(
				array(
					array(
						'param'    => 'post_type',
						'operator' => '==',
						'value'    => 'page',
					),
				),
			),
			'menu_order'            => 1,
			'position'              => 'normal',
			'style'                 => 'seamless',
			'label_placement'       => 'top',
			'instruction_placement' => 'label',
			'hide_on_screen'        => array(
				0 => 'the_content',
				1 => 'comments',
				2 => 'send-trackbacks',
			),
			'active'                => 1,
			'description'           => '',
		)
	);

endif;
